"""
Tool: open_pr

After propose_patch has written a patched file to agent/patches/,
this tool:
  1. Creates a new branch off main
  2. Copies the patched file over pipelines/jobs/transactions_etl.py
  3. Commits with a semantic message
  4. Pushes the branch to origin
  5. Opens a Pull Request via the GitHub REST API
  6. Returns the PR URL and number

Requires environment variables:
  GITHUB_TOKEN  - fine-grained PAT with contents:write + pull-requests:write
  GITHUB_REPO   - "owner/repo" (e.g. "CristianCaro-portfolio/spark-self-heal")

Assumes the local repo has 'origin' pointing to the GitHub repo and that
the working tree is clean (no uncommitted changes) before the call.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path

import requests

PIPELINE_PATH = Path("pipelines/jobs/transactions_etl.py")
DEFAULT_BASE_BRANCH = "main"


SCHEMA = {
    "name": "open_pr",
    "description": (
        "Opens a pull request on GitHub with the proposed patch. "
        "Creates a new branch, applies the patch from agent/patches/, "
        "commits, pushes, and opens a PR against main. "
        "Call this AFTER propose_patch has succeeded. "
        "The agent must pass the same fm_id, summary, rationale, and "
        "diagnosis evidence used in propose_patch so the PR description "
        "is self-contained."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "fm_id": {
                "type": "string",
                "description": "Failure mode ID (e.g. 'FM-06').",
            },
            "patch_path": {
                "type": "string",
                "description": (
                    "Path to the patched file produced by propose_patch, "
                    "e.g. 'agent/patches/FM-06__20260520T145556Z.py'."
                ),
            },
            "summary": {
                "type": "string",
                "description": "One-sentence summary of the fix (used in PR title).",
            },
            "evidence": {
                "type": "string",
                "description": "Literal log excerpt from the diagnosis.",
            },
            "rationale": {
                "type": "string",
                "description": "2-4 sentences explaining the fix.",
            },
            "glue_job_run_id": {
                "type": "string",
                "description": "Glue JobRunId that triggered this PR (for traceability).",
            },
        },
        "required": [
            "fm_id", "patch_path", "summary",
            "evidence", "rationale", "glue_job_run_id",
        ],
    },
}


def _run(cmd: list[str]) -> tuple[int, str, str]:
    """Run a shell command, return (returncode, stdout, stderr)."""
    proc = subprocess.run(
        cmd, capture_output=True, text=True, check=False,
    )
    return proc.returncode, proc.stdout.strip(), proc.stderr.strip()


def _git(*args: str) -> tuple[int, str, str]:
    return _run(["git", *args])


def _check_clean_worktree() -> str | None:
    """Return None if clean, otherwise a description of what's dirty."""
    rc, out, _ = _git("status", "--porcelain")
    if rc != 0:
        return "git status failed"
    if out:
        return f"working tree has uncommitted changes:\n{out}"
    return None


def _pr_body(fm_id: str, evidence: str, rationale: str,
             glue_job_run_id: str, patch_path: str) -> str:
    return f"""\
## Self-healing PR -- diagnosed and proposed by the spark-self-heal agent

**Failure mode:** `{fm_id}`

### Evidence (literal log excerpt)
```
{evidence[:500]}
```

### Rationale
{rationale}

### Provenance
- **Glue JobRunId**: `{glue_job_run_id}`
- **Patch artifact**: `{patch_path}`
- **Generated at**: {datetime.now(timezone.utc).isoformat()}

### Reviewer checklist
- [ ] CI (pytest) is green
- [ ] Diff is minimally invasive (no unrelated refactors)
- [ ] Patch matches the `Proposed remediation` for {fm_id} in
      `docs/failure-modes.md`
- [ ] If approved: merge and trigger `transactions_etl` DAG to verify
      the next run succeeds

---

*Generated by the spark-self-heal agent. Mode: `propose` (see ADR-002).*
*A human must review and merge.*
"""


def execute(fm_id: str, patch_path: str, summary: str, evidence: str,
            rationale: str, glue_job_run_id: str) -> dict:
    """Open a PR with the proposed patch. Returns PR url + number on success."""

    token = os.getenv("GITHUB_TOKEN")
    repo = os.getenv("GITHUB_REPO")
    if not token or not repo:
        return {"error": "GITHUB_TOKEN and GITHUB_REPO env vars are required."}

    patch = Path(patch_path)
    if not patch.exists():
        return {"error": f"Patch file not found: {patch_path}"}

    dirty = _check_clean_worktree()
    if dirty:
        return {"error": f"refusing to open PR -- {dirty}"}

    rc, _, err = _git("checkout", DEFAULT_BASE_BRANCH)
    if rc != 0:
        return {"error": f"git checkout {DEFAULT_BASE_BRANCH} failed: {err}"}

    rc, _, err = _git("pull", "--ff-only", "origin", DEFAULT_BASE_BRANCH)
    if rc != 0:
        return {"error": f"git pull failed: {err}"}

    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    branch = f"fix/{fm_id.lower()}-{ts}"
    rc, _, err = _git("checkout", "-b", branch)
    if rc != 0:
        return {"error": f"git checkout -b {branch} failed: {err}"}

    shutil.copyfile(patch, PIPELINE_PATH)

    rc, _, err = _git("add", str(PIPELINE_PATH))
    if rc != 0:
        return {"error": f"git add failed: {err}"}

    commit_msg = (
        f"fix(pipeline): {summary}\n\n"
        f"Auto-generated by the spark-self-heal agent.\n"
        f"Failure mode: {fm_id}\n"
        f"Source patch: {patch_path}\n"
        f"Glue JobRunId: {glue_job_run_id}\n"
    )
    rc, _, err = _git("commit", "-m", commit_msg)
    if rc != 0:
        return {"error": f"git commit failed: {err}"}

    # Push using the token explicitly so it works regardless of the local
    # credential helper (CI, fresh checkout, etc.).
    # Note: no -u/--set-upstream on purpose -- that would persist the
    # token-embedded URL into .git/config. We push once with the URL inline
    # and leave the local branch with no upstream tracking.
    push_url = f"https://x-access-token:{token}@github.com/{repo}.git"
    rc, _, err = _run([
        "git", "push", push_url,
        f"{branch}:refs/heads/{branch}",
    ])
    if rc != 0:
        _git("checkout", DEFAULT_BASE_BRANCH)
        return {"error": f"git push failed: {err}"}

    api = f"https://api.github.com/repos/{repo}/pulls"
    body = _pr_body(fm_id, evidence, rationale, glue_job_run_id, patch_path)
    payload = {
        "title": f"fix({fm_id}): {summary}",
        "head": branch,
        "base": DEFAULT_BASE_BRANCH,
        "body": body,
        "draft": False,
    }
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    try:
        resp = requests.post(api, headers=headers, json=payload, timeout=30)
    except requests.RequestException as e:
        _git("checkout", DEFAULT_BASE_BRANCH)
        return {"error": f"GitHub API request failed: {e}"}

    if resp.status_code >= 300:
        _git("checkout", DEFAULT_BASE_BRANCH)
        try:
            details = resp.json()
        except ValueError:
            details = resp.text[:500]
        return {
            "error": f"GitHub API returned {resp.status_code}",
            "details": details,
        }

    pr = resp.json()
    _git("checkout", DEFAULT_BASE_BRANCH)

    return {
        "pr_url": pr["html_url"],
        "pr_number": pr["number"],
        "branch": branch,
        "title": pr["title"],
        "state": pr["state"],
    }
